apply from: '../../constants.gradle'
apply plugin: 'com.android.library'

android {
  namespace "org.lsposed.hiddenapibypass.library"

  compileSdkVersion project.ext.compileSdkVersion
  buildToolsVersion project.ext.buildToolsVersion

  compileOptions {
    sourceCompatibility project.ext.javaVersion
    targetCompatibility project.ext.javaVersion
  }

  defaultConfig {
    minSdkVersion    project.ext.minSdkVersion
    targetSdkVersion project.ext.targetSdkVersion
  }

  buildFeatures {
    buildConfig true
  }

  lintOptions {
    disable 'MissingTranslation'
    abortOnError true
  }
}
